build: false
shallow_clone: true
platform: 'x86'
branches:
  except:
    - gh-pages

services:
- mysql56
- postgresql93

install:
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y curl
  - SET PATH=C:\Program Files\curl;%PATH%
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_pdo_pgsql.dll >> php.ini
  - echo extension=php_pgsql.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist -n --no-ansi

test_script:
  - php codecept run cli --no-colors -n --skip-group coverage
  - php codecept run unit -g core -g appveyor --no-colors -n