build: false
platform: 'x86'
branches:
  except:
    - gh-pages

cache:
  - c:\tools\php71 -> appveyor.yml

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php71;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  # php setup
  - IF EXIST c:\tools\php71 (SET PHP=0)
  - ps: Set-Service wuauserv -StartupType Manual
  - IF %PHP%==1 cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y curl
  - SET PATH=C:\Program Files\curl;%PATH%
  - sc config wuauserv start= auto
  - IF %PHP%==1 cinst -y php --version 7.1.14
  - IF %PHP%==1 cd c:\tools\php71
  - IF %PHP%==1 copy php.ini-production php.ini
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_pdo_sqlite.dll >> php.ini
  - SET PATH=C:\tools\php71;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist -n --no-ansi

test_script:
  - codecept run cli --no-colors -n --skip-group coverage
  - codecept run unit -g core -g appveyor --no-colors -n
